import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;


/**
 * <h1>CargoPlane</h1> Represents a Cargo Plane
 */
public class CargoPlane extends Vehicle {

    private String licensePlate;
    private double maxWeight;
    private double currentWeight;
    private int zipDest;
    private ArrayList <Package> packages = new ArrayList<Package>();
    final double GAS_RATE = 2.33;

    /**
     * Default Constructor
     */
    public CargoPlane () {
        super ();
    }

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */

    public CargoPlane (String licensePlate, double maxWeight) {
        super (licensePlate, maxWeight);
    }


    public String getLicensePlate() {
        return this.licensePlate;
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    public double getMaxWeight() {
        return this.maxWeight;
    }

    public void setMaxWeight(double maxWeight) {
        this.maxWeight = maxWeight;
    }

    public double getCurrentWeight() {
        return this.currentWeight;
    }

    public int getZipDest() {
        return this.zipDest;
    }

    public void setZipDest(int zipDest) {
        this.zipDest = zipDest;
    }

      public ArrayList <Package> getPackages() {
        return this.packages;
    }


    /**
     * Overides its superclass method. Instead, after each iteration, the range will
     * increase by 10.
     *
     * @param warehousePackages List of packages to add from
     */
    public void fill(ArrayList<Package> warehousePackages) {

        int range = 0;
        int number = 0;
        int numberOfPack = warehousePackages.size();


        while (!isFull() && number < numberOfPack) {
            for (int i = 0; i < warehousePackages.size(); i++) {
                int difference = Math.abs(this.zipDest - warehousePackages.get(i).getDestination().getZipCode());
                if (((difference == range))) {
                    number++;
                    if (this.currentWeight + warehousePackages.get(i).getWeight() <= maxWeight) {
                        addPackage(warehousePackages.get(i));
                        warehousePackages.remove(i);
                        this.currentWeight += warehousePackages.get(i).getWeight();
                        i = i - 1;
                    }

                }

            }
            range = range + 10;
        }
    }






    /**
     * Returns the profits generated by the packages currently in the Cargo Plane.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 2.33)
     * </p>
     */

    NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.US);

    @Override
    public double getProfit() {
        double profit = 0.0;
        double priceOfPackage = 0.0;
        int maxRange = 0;
        int range = 0;

        for (int i = 0; i < packages.size(); i++) {
            range = Math.abs(getZipDest() - getPackages().get(i).getDestination().getZipCode());
            if (range > maxRange) {
                maxRange = range;
            }
            priceOfPackage = packages.get(i).getPrice();
            profit += priceOfPackage;
        }

        profit -= (maxRange * GAS_RATE);

        return profit;
    }


    /**
     * Generates a String of the Cargo Plane report. Cargo plane report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in cargo plane</li>
     * </ul>
     *
     * @return Cargo Plane Report
     */
    @Override
    public String report() {
        String endResult = "";

        /////cargo plane report

        String cargoPlane = "==========CargoPlane Report==========";
        String license = "License Plate No.: " + this.licensePlate;
        String destination = "Destination: " + this.zipDest;
        String weightLoad = String.format("Weight load: %.2f" + "/%.2f", this.currentWeight, this.maxWeight);
        String netProfit = "Net Profit: " + nf.format(this.getProfit());
        String shippingLabels = "=====Shipping Labels=====";
        String dash = "====================";


        ///////shipping labels

        for (int i = 0; i <packages.size(); i++) {
            endResult += "\n" + packages.get(i).shippingLabel();
        }

        return cargoPlane + "\n" + license + "\n" + destination + "\n" + weightLoad + "\n" + netProfit
                + "\n" + shippingLabels + endResult;
    }
}